### ISSUE TITLE
Request: support for ellipsis character

### ISSUE THREAD

**Issue by markmercier** [FontKai-Kaisei/Kaisei#2]
Hello there! I've been using this font (via Google Fonts) for a website but discovered that it doesn't seem to support the ellipsis character (…). Here are some details about the character code: https://www.compart.com/en/unicode/U+2026

This is how it renders on Kaisei (3 dots at the midpoint, rather than roughly 3 periods):
![Screen Shot 2021-12-15 at 12 52 19 PM](https://user-images.githubusercontent.com/40346176/146263305-645155fd-87b5-4cba-8c53-d3a166eda7fd.jpg)

Expected behavior (faked with 3 periods):
![Screen Shot 2021-12-15 at 1 02 05 PM](https://user-images.githubusercontent.com/40346176/146264505-a2b4f421-de71-4aa8-9adf-a95c856ac1cc.jpg)

The ellipsis is tricky because many programs automatically convert 3-periods into one ellipsis, so even though it may not be a character many people will type directly, it can sneak into text unexpectedly.

For now, I'm just going to write a script to counteract this, but it'd be great for that support to be added to the font so other people can use it!

**Comment by aaronbell** [comment]
Thanks for the issue report. The font does support the ellipsis character, but as you've noted, it is positioned along the centerline rather than at the baseline. This is actually common for Japanese fonts, and aligns with the other 'expert' Japanese fonts offered in Google Fonts. As this font is primarily intended for a Japanese audience, we do not intend to make a change in the ellipsis' design. Sorry for the trouble!

If you really want to use a version of the ellipsis along the baseline, the full-width version of the glyph has it thusly positioned.
